set (CPACK_PACKAGE_VENDOR "Paul Scherrer Institut")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Control System Data in QtQuick")
set (CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_SOURCE_DIR}/README.rst)
seT (CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set (CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.rst)
set (CPACK_PACKAGE_VERSION_MAJOR ${CSDATAQUICK_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${CSDATAQUICK_VERSION_MINOR})
set (CPACK_PACKAGE_VERSION_PATCH ${CSDATAQUICK_VERSION_RELEASE})
set (CPACK_PACKAGE_EXECUTABLES ADLViewer ADLViewer builder "Quick Builder" QtCreator "Qt Quick Designer")
set (CPACK_MONOLITHIC_INSTALL TRUE)

if (APPLE)
    set (CPACK_GENERATOR "DragNDrop")
    set (CPACK_PACKAGING_INSTALL_PREFIX "/CSDataQuick")
endif()

# Include Qt Creator
if (QTC_PACKAGE)
    set (CPACK_INSTALLED_DIRECTORIES ${QTC_PACKAGE} ".")
endif()

include(CPack)
