on: [push]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Qt
        run: sudo apt install qtbase5-dev qtdeclarative5-dev qt5-default qdoc-qt5 qt5-doc-html
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          conda-build-version: 3
          auto-activate-base: true
          activate-environment: ""
          channels: paulscherrerinstitute
      - name: Run CMake
        run: |
          conda info
          conda activate base
          conda install epics-base
          mkdir build
          cd build
          cmake ..
      - name: Build docs
        run: |
            cd build
            make html-offline
