on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Qt
        run: sudo apt install qtbase5-dev qtdeclarative5-dev qt5-default qdoc-qt5 qt5-doc-html
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          auto-activate-base: true
          activate-environment: ""
          channels: paulscherrerinstitute
      - name: Run CMake
        run: |
          conda activate base
          conda install epics-base
          mkdir build
          cd build
          cmake ..
      - name: Build docs
        run: make html-offline
